# Generated by Django 2.2.11 on 2020-03-22 00:23

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleMarkov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngram_size', models.PositiveSmallIntegerField(default=5)),
                ('source_file', models.FileField(upload_to='sources/')),
                ('markov_model', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='MergedMarkov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngram_size', models.PositiveSmallIntegerField(default=5)),
                ('merged_model', picklefield.fields.PickledObjectField(editable=False)),
                ('source_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_one', to='MarkovApp.SingleMarkov')),
                ('source_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_two', to='MarkovApp.SingleMarkov')),
            ],
        ),
    ]
